# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobile_base/joy.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class joy(genpy.Message):
  _md5sum = "65a21cca78a5147fa5f897d0fbef56fe"
  _type = "mobile_base/joy"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool dirA
bool dirB
int16 speedA
int16 speedB"""
  __slots__ = ['dirA','dirB','speedA','speedB']
  _slot_types = ['bool','bool','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dirA,dirB,speedA,speedB

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(joy, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.dirA is None:
        self.dirA = False
      if self.dirB is None:
        self.dirB = False
      if self.speedA is None:
        self.speedA = 0
      if self.speedB is None:
        self.speedB = 0
    else:
      self.dirA = False
      self.dirB = False
      self.speedA = 0
      self.speedB = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2h().pack(_x.dirA, _x.dirB, _x.speedA, _x.speedB))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.dirA, _x.dirB, _x.speedA, _x.speedB,) = _get_struct_2B2h().unpack(str[start:end])
      self.dirA = bool(self.dirA)
      self.dirB = bool(self.dirB)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2h().pack(_x.dirA, _x.dirB, _x.speedA, _x.speedB))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.dirA, _x.dirB, _x.speedA, _x.speedB,) = _get_struct_2B2h().unpack(str[start:end])
      self.dirA = bool(self.dirA)
      self.dirB = bool(self.dirB)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2h = None
def _get_struct_2B2h():
    global _struct_2B2h
    if _struct_2B2h is None:
        _struct_2B2h = struct.Struct("<2B2h")
    return _struct_2B2h
